### ISSUE TITLE
macOS Patcher supports acceleration

### ISSUE THREAD

**Issue by julianfairfax** [wolfiediscord/website#1]
In this repository, and I'm sure in other places, it's claimed that macOS Patcher doesn't support graphics acceleration. This is incorrect. macOS Patcher supports acceleration on all devices that support acceleration through the use of other patches. This does not include the MacBook4,1 as it isn't supported by other patchers, and wouldn't support graphics acceleration if it were. Please rectify this error wherever possible. Thank you!

**Comment by wolfiediscord** [comment]
Hi! Thanks for creating an issue. The website guide is outdated, and I will be sure to mention that. I have created a [Github Gist](https://gist.github.com/wolfiediscord/d02d5d30898c8cacd6b5c1ab83af95b9) instead, and will make the changes accordingly. Thank you for your feedback.

**Comment by julianfairfax** [comment]
Thank you

**Comment by julianfairfax** [comment]
I'm not necessarily supporting them but I'm also not not supporting them anymore. Updates are actually coming soon.

**Comment by wolfiediscord** [comment]
This has been implemented.

**Comment by julianfairfax** [comment]
I don't know why only OS X Patcher is listed and why it's only listed for Yosemite and El Capitan, since it also supports Mountain Lion and Mavericks, but it's actually incorrect that it only doesn't support accel on the MacBook4,1. OS X Patcher doesn't support accel on any Mac, but macOS Patcher only doesn't support accel on the MacBook4,1.

**Comment by wolfiediscord** [comment]
I haven't listed them since they weren't getting updates. I'll fix it soon.
